name: Integration

on:
  push:
    branches:
      - release
      - release-keep-version
      - integration
      - integration-*
      - next
      - next-*
      - nightly
      - latest
  pull_request:
    branches: [latest]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install
        run: yarn install --immutable
      - name: Ensure deps are deduped
        run: yarn dedupe --check
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Format
        run: yarn format
      - name: Lint
        run: yarn lint
      - name: Release
        run: yarn release
        env:
          NIGHTLY_BRANCH: nightly
          RELEASE_BRANCH: release
          RELEASE_KEEP_VERSION_BRANCH: release-keep-version
          INTEGRATION_BRANCH: integration
          NEXT_BRANCH: next
          STABLE_BRANCH: stable
          LATEST_BRANCH: latest
          PUBLIC_REPO_TOKEN: ${{secrets.PUBLIC_REPO_TOKEN}}
          EMAIL_ADDRESS: ${{secrets.EMAIL_ADDRESS}}
          GIT_NAME: ${{secrets.GIT_NAME}}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          npmAuthToken: ${{secrets.NPM_PUBLISH_TOKEN}}
          YARN_NPM_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
